### ISSUE TITLE
Fix copyright headers

### ISSUE THREAD

**Issue by jespersmith** [Halodi/eve-ros2-examples#9]
Current copyright headers are 2016 @ OSRF, should be 2021 @ Halodi

**Comment by jespersmith** [comment]
In general I agree, but in the case of examples that will be copied outside the repo and not necessary stay together per-file copyright headers probably make sense

**Comment by nnadeau** [comment]
Most license files have a clause that the LICENSE shall be kept with copies.

e.g., MIT:
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

So people copying it outside the repo are technically in breach. 😛 
Otherwise, we should have a LICENSE file in the repo regardless. 

If we also still want a copyright header, let's make sure it's consistent, maintained, and automated:

- Linter tool: https://github.com/google/addlicense
- GH action to ensure maintenance: https://github.com/amundsen-io/amundsendatabuilder/blob/master/.github/workflows/license.yml
